In [1]:
print("dsp")

dsp


In [2]:
import numpy as np
import pandas as  pd
import matplotlib.pyplot as plt
import  statsmodels.api as sm
import seaborn
seaborn.set()

In [3]:
data = pd.read_csv("1.02. Multiple linear regression.csv")

In [4]:
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [5]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

In [6]:
y = data['GPA']
x1 = data[['SAT','Rand 1,2,3']]

In [7]:
x = sm.add_constant(x1)
results = sm.OLS(y,x).fit()

In [8]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    GPA   R-squared:                       0.407
Model:                            OLS   Adj. R-squared:                  0.392
Method:                 Least Squares   F-statistic:                     27.76
Date:                Tue, 06 Jul 2021   Prob (F-statistic):           6.58e-10
Time:                        09:13:35   Log-Likelihood:                 12.720
No. Observations:                  84   AIC:                            -19.44
Df Residuals:                      81   BIC:                            -12.15
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2960      0.417      0.710      0.480      -0.533       1.125
SAT            0.0017      0.000      7.432      0.000       0.001       0.002
Rand 1,2,3    -0.0083      0.027     -0.304      0.762      -0.062       0.046
==============================================================================
Omnibus:                       12.992   Durbin-Watson:                   0.948
Prob(Omnibus):                  0.002   Jarque-Bera (JB):               16.364
Skew:                          -0.731   Prob(JB):                     0.000280
Kurtosis:                       4.594   Cond. No.                     3.33e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.33e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# カテゴリ変数練習(section33)

In [9]:
data = pd.read_csv('1.03. Dummies.csv')

In [10]:
data

SAT   GPA Attendance
0   1714  2.40         No
1   1664  2.52         No
2   1760  2.54         No
3   1685  2.74         No
4   1693  2.83         No
..   ...   ...        ...
79  1936  3.71        Yes
80  1810  3.71        Yes
81  1987  3.73         No
82  1962  3.76        Yes
83  2050  3.81        Yes

[84 rows x 3 columns]

In [11]:
data['Attendance']=data['Attendance'].map({'Yes':1,'No':0})

In [12]:
data

SAT   GPA  Attendance
0   1714  2.40           0
1   1664  2.52           0
2   1760  2.54           0
3   1685  2.74           0
4   1693  2.83           0
..   ...   ...         ...
79  1936  3.71           1
80  1810  3.71           1
81  1987  3.73           0
82  1962  3.76           1
83  2050  3.81           1

[84 rows x 3 columns]

In [13]:
data.describe()

SAT        GPA  Attendance
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    0.464286
std     104.530661   0.271617    0.501718
min    1634.000000   2.400000    0.000000
25%    1772.000000   3.190000    0.000000
50%    1846.000000   3.380000    0.000000
75%    1934.000000   3.502500    1.000000
max    2050.000000   3.810000    1.000000

In [14]:
y = data['GPA']
x1 = data[['SAT','Attendance']]

In [15]:
x = sm.add_constant(x1)
results = sm.OLS(y,x).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    GPA   R-squared:                       0.565
Model:                            OLS   Adj. R-squared:                  0.555
Method:                 Least Squares   F-statistic:                     52.70
Date:                Tue, 06 Jul 2021   Prob (F-statistic):           2.19e-15
Time:                        09:13:36   Log-Likelihood:                 25.798
No. Observations:                  84   AIC:                            -45.60
Df Residuals:                      81   BIC:                            -38.30
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6439      0.358      1.797      0.076      -0.069       1.357
SAT            0.0014      0.000      7.141      0.000       0.001       0.002
Attendance     0.2226      0.041      5.451      0.000       0.141       0.304
==============================================================================
Omnibus:                       19.560   Durbin-Watson:                   1.009
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.189
Skew:                          -1.028   Prob(JB):                     1.25e-06
Kurtosis:                       4.881   Cond. No.                     3.35e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.35e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [16]:
test_data = pd.DataFrame({'const': 1, 'SAT':[1700,1670],'Attendance':[0,1]})
test_data

const   SAT  Attendance
0      1  1700           0
1      1  1670           1

In [17]:
predictions = results.predict(test_data)
predictions

0    3.023513
1    3.204163
dtype: float64

# SKLearn練習

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
data = pd.read_csv('1.01.Simple-linear-regression.csv')
data

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

In [20]:
x = data['SAT']
y = data['GPA']
x.shape
y.shape

(84,)

In [21]:
x = x.values.reshape(-1,1)
x.shape

(84, 1)

In [22]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [23]:
# R値,モデルの説明力
reg.score(x,y)

0.40600391479679765

In [24]:
# 相関係数
reg.coef_

array([0.00165569])

In [25]:
reg.predict(np.array(1740).reshape(1,-1))

array([3.15593751])

In [26]:
test_data = pd.DataFrame(data=[1740,1760],columns=['SAT'])
test_data

SAT
0  1740
1  1760

In [27]:
test_data['kigaku_GPA']=reg.predict(test_data)
test_data

SAT  kigaku_GPA
0  1740    3.155938
1  1760    3.189051

# 重回帰分析

In [28]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [29]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [30]:
# LinearRegressionは重回帰前提なのでreshapeする必要なし
reg.fit(x,y)

LinearRegression()

In [31]:
# 決定係数ここではR2乗値自由度修正済み(どうでもいい値が入っていることを考慮して正しい説明力を示している値)にはならない。
#自由度修正済みの方が小さくなれば一つ以上の変数は全く当てにならないことを示す。

reg.score(x,y)

0.40668119528142843

In [32]:
# 特徴選択
from sklearn.feature_selection import f_regression
f_regression(x,y)
#右がF値, 左がP値
# 一つ一つが意味あるかないかはわかるが、相互作用は考慮していない。考慮するならlinearlegressionを使う 

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [33]:
# 標準化
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)

StandardScaler()

In [34]:
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [35]:
reg.fit(x_scaled,y)

LinearRegression()

In [36]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [37]:
# この回帰による結果をデータフレーム型で表示,Biasは切片
reg_summary = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']],columns=['Features'])
reg_summary['Weights'] = reg.intercept_,reg.coef_[0],reg.coef_[1]
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [38]:
#Random1,2,3を除く
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
reg.fit(x_simple_matrix,y)

LinearRegression()

In [39]:
reg.coef_

array([0.1720369])

# train test

In [43]:
from sklearn.model_selection import train_test_split
a = np.arange(1,101)
b = np.arange(501,601)

In [49]:
a_train, a_test, b_train, b_test = train_test_split(a,b,test_size = 0.2,random_state=42)
# random_stateに入れるとずっと変わらない
a_train.shape

(80,)