In [1]:
import numpy as np

In [2]:
m = np.array([[5,12,6],[-3,0,14]])

In [3]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [4]:
type(m)

numpy.ndarray

In [6]:
#次元を示す
m.shape

(2, 3)

In [7]:
m2 = np.array([[9,8,7],[1,3,-5]])
#テンソル作成
t = np.array([m,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [8]:
t.shape

(2, 2, 3)

In [9]:
#転置
m.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [11]:
#ベクトルを転置する場合
x = np.array([1,2,3])
x_reshape = x.reshape(1,3)
x_reshape.T

array([[1],
       [2],
       [3]])

In [15]:
#行列の掛け算
s = np.array([[1,2,3],[4,5,6]])
np.dot(m,s.T)

array([[ 47, 116],
       [ 39,  72]])